### PR TITLE
Added spanish translation.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ltguillaume** [comment]
Thank you so much! I'll release v6.1 with Spanish as soon as I have word from the ppl who experienced an issue with v6.0 on Android v6 (Marshmallow).

**Comment by ghost** [comment]
You're wellcome! I'll check it the translation when the app reach f-droid. Although I think everything is correct, maybe there some mismatch with gender of words and so.

BTW: I use the app and I'm very happy with it. Thank for coding it :)

**Comment by ltguillaume** [comment]
No worries man, you can always create another pull request to fix things.
Cheers!

**Comment by ltguillaume** [comment]
@helfio you can try this test version to check if the translations are correct.
https://github.com/ltGuillaume/DroidShows/releases/download/6.0/DroidShows_6.1TEST.apk
Cheers!

**Pull request merged**
