### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by Jiack214**

### CODE REVIEW

**Comment by ltguillaume** [comment]
Thank you!

**Comment by ltguillaume** [comment]
Here's a compiled version, so you can test/make improvements.
[DroidShows_7.7.2IT.zip](https://github.com/ltGuillaume/DroidShows/files/1467701/DroidShows_7.7.2IT.zip)

**Comment by ltguillaume** [comment]
I also need a translation for:
> Use for daily backups

something like
> Usa per i backup quotidiani

???

**Comment by Jiack214** [comment]
I have already compiled it myself, thanks anyway.

Yes, "Usa per i backup quotidiani" is correct.

**Pull request merged**
